### ISSUE TITLE
allow data interchange between tabs

### ISSUE THREAD

**Issue by janmotum** [adrianmay/rhaboo#20]
currently it is not possible to load data in localStorage in tab1 and use this data in tab2.

The "built" variable keeps a local copy of the variables, and this will be used even when creating a new Rhaboo persistent object.   Maybe add some reset() function to clean the local cache so the data is fetched again from the local storage

**Comment by adrianmay** [comment]
Just call the constructor again and assign the result to the same variable so the old one drops out of scope. I'm pretty sure that'll work but I won't be able to try it before Monday. If you do, please post the result here so everybody knows. Then I'll document it cos it's a good question.

Thanks, Adrian.

**Comment by janmotum** [comment]
I created a test page in the demo's to show the error.  It is also "broken" when using frames.
https://github.com/janmotum/rhaboo/commit/d318d34baecec8f5b5092fd39f3499c472dfe3f2

**Comment by adrianmay** [comment]
Sorry I didn't notice you'd responded to this already. 

I'm not sure what you think is wrong. With your frames demo, I can reload one frame several times to increase the counter in that frame to e.g. 5, then if I reload the whole page, both frames will say 6. Is that what you observe? To me that seems like the correct behaviour. In theory you can hook the storage event to get the other tab/frame to update faster, but I didn't try it yet:   http://truongtx.me/2014/06/16/cross-tab-communication-using-html5-dom-storage/

What I did notice is that when localStorage is truly empty (use localStorage.clear() ) then there's a crash half way through onLoad of the second frame. Is that what you meant? I'm working on that now.

**Comment by janmotum** [comment]
what I would expect is that the other frame can view the updated data without reloading

* reload top frame several times.  the data in the top frame is updated as expected
* click "Reload data" in the bottom frame.   My expectation is that it would show the same data as in the top frame.   But it shows the data from the time the bottom frame was loaded.

to reload data, a new store is created.  But even with a new store, it doesn't really reload the data from the localStorage.   If it was loading data from a store that is defined global, that would be OK if it didn't showed the very last data.

**Comment by janmotum** [comment]
In this last commit I did a quick & dirty workaround in the rabhoo.max.js (I'm not familiar with node.js, so I hacked it in the compiled js file)

I've added a reset function that clears the cache so data is updated without reloading the tabs

**Comment by adrianmay** [comment]
I made a frames demo like yours at demos/frames.html.

We seem to agree that in the current version, no matter what order you reload the frames in, the number shown by the frame you just reloaded is the total number of reloads. Right? (Except there's a thread safety bug if you reload both at the same time.)

I'd say that was the correct behaviour. You seem to be saying that doing a reload in the second frame shouldn't update the counter, but why not? Perhaps it was just goofy to count reloads at all and I should be counting button clicks to avoid the confusion.

How about if there was a notification mechanism so the other frame could be prodded into re-displaying the counter (but not incrementing it) when the value of the counter changes for any reason, such as the first frame being reloaded? Would that serve your purposes?

**Comment by adrianmay** [comment]
Hang on, seems like you're right. I got the notifier working but it still doesn't read the proper value. Let me try it with your built={} trick....

**Comment by janmotum** [comment]
I made little video of what I'm doing.   We were using "reload" in too 
many different cases

https://youtu.be/nMusMMsnzig

top frame: reloading the frame
bottom frame: reloading the data by creating a new store and updating 
the displayed value via javascript

the last click is reset and reload what first clears the  internal built 
variable

**Comment by adrianmay** [comment]
Thanks for this conversation. The real deal is that I should always set built={} at the end of the constructor. I knew that but forgot. So you don't need reset.

I now have the notification demo and I'll commit it in the next few minutes.

**Comment by adrianmay** [comment]
OK it's up. Try demos/notiframes.html
