### ISSUE TITLE
Conflict with jPages

### ISSUE THREAD

**Issue by Poper123** [adrianmay/rhaboo#28]
Hello Adrian,

I like your library. But now there is a conflict with jPages.

* jQuery jPages v0.7
 * Client side pagination with jQuery
 * http://luis-almeida.github.com/jPages

Can you help me?

**Comment by adrianmay** [comment]
Hi,

I'd love to help but I'll need some more info as to what the problem is. Can you make a demo page?

Adrian.

**Comment by Poper123** [comment]
Here the demo page:
http://www.ihsl.de/test/test.html
If rhaboo is active the layers/pages are without content.

**Comment by adrianmay** [comment]
OK thanks for the demo. I'm looking at it, but I'm away this weekend so it'll have to wait until after that.

**Comment by adrianmay** [comment]
I added a version called rhaboo.jpages.max.js which seems to work around the problem. Hopefully this enables you to keep working until I can fix it for real. If this version also gives trouble, please let me know.

**Comment by Poper123** [comment]
Perfect. You save my weekend.
You are wonderful. Thanks a lot.

**Comment by adrianmay** [comment]
I noticed you're using jquery-1.8.2. When I test the standard rhaboo against the current jquery versions, e.g. 1.11.2 or 2.1.3, it works fine. So I suggest you try that and forget that temporary version I made.

**Comment by adrianmay** [comment]
I published a modified version of your demo so I can keep testing this jPages thing through future updates. Hope you don't mind.

**Comment by adrianmay** [comment]
BTW, I did have a bug causing this: I forgot to return anything from the modified array push. So thanks for the heads up!
