### ISSUE TITLE
Which source to use?

### ISSUE THREAD

**Issue by kokujin** [adrianmay/rhaboo#30]
I have my own assets management stack. I concatenate and minify all my JS files with a Gulp task, which source should I use? You have several and I could not find out the exact differences in the docs. Thanks

**Comment by adrianmay** [comment]
I don't know much about gulp. I use grunt on rhaboo. But if you want a regular JS script, use rhaboo.min.js or rhaboo.max.js in the root directory.

**Comment by kokujin** [comment]
Thanks
