### ISSUE TITLE
DOM Exception 22 corrupts the storage

### ISSUE THREAD

**Issue by unematiii** [adrianmay/rhaboo#31]
What would be the correct way to handle storage quota exceptions? I'm not able to instantiate Rhaboo.persistent after that (quota exceeded) happens:

```javascript
TypeError: null is not an object (evaluating 'x.split')
```

**Comment by adrianmay** [comment]
I'm aware of this but I didn't start working on it yet. There's another issue about hitting the storage limit already. 

I suppose there might be a way for the rhaboo layer to diagnose the problem and barf at the feature layer, but does that really help? 

To me it seems that if there's any chance at all of that volume of data being stored locally then the design is already wrong. If it's 5MB of real, user-generated data, and not just somebody filling an array with zeros for the hell of it, then it's probably too valuable to live in such a volatile place.

**Comment by unematiii** [comment]
I agree about the design. This is a work in progress, we are caching a lot of data..

But anyway, "I suppose there might be a way for the rhaboo layer to diagnose the problem and barf at the feature layer, but does that really help?" -- I think the critical part here is not to corrupt the storage scheme <--- I have to flush everything to get the `localStorage` working again. I haven't had much time to go into depths of exploring the source, but I was thinking about catching the error, and somehow make sure that the `nextSlot`wouldn't point to nonexistent entry...

**Comment by adrianmay** [comment]
So I did something. If writing to a slot fails, I just allow the slot to not exist. In fact I erase it just in case there's junk in there. When restoring, this ain't such a big deal - I just return undefined. There are two functions where that can happen: restore() where we're reading a slot we know (notwithstanding quota exceptions) to contain an object; and augment() where we're adding a property to an object we're in the middle of restore()ing. Either way you just get a gap.

I tested that it still works before the quota gets tight, but I didn't get around to testing it when the quota is exceeded. If you already have a test where it's exceeded, perhaps you let me know how it goes :-)

**Comment by unematiii** [comment]
Okay, tested this on Chrome & Safari. I'm also logging the slot no where the exception occurred, lets denote that with *p*. This slot is indeed removed. ```_RHABOO_NEXT_SLOT``` has value *p+1*. In my case, the slot *p-1* has value ```?t;source=p```, where *p* is obviously st that doesn't exist. This will throw an exception:

```
TypeError: null is not an object (evaluating 'x.split')
```

Also, it might be a good idea to re-throw the exception (DOM 22), so that who ever is using the lib, will also know this is the case.

**Comment by adrianmay** [comment]
Hi Mati,

You're being quite active on rhaboo and i think you should have the credit for that in github. I'm not sure how that works, but I noticed you already forked rhaboo and I'm guessing that your name would somehow pop up on rhaboo if I accepted a pull request from you. For instance, if you just wrote that test for the full memory, then you could put it under manual-tests, upload it to your fork and send me the pull request. Would you like to try?

Adrian.

**Comment by unematiii** [comment]
Hi Adrian,

Sorry, I've been extremely busy lately. We are using Rhaboo for one of our projects ;), I really haven't built any tests so far. My observations come from recent builds. Since I was experiencing performance issues on iOS (Safari, inc chromeless) - it tends to crash when you write relatively large amounts of data, approx >= 64Kb, I decided to go with Rocks implementation instead. This also solved the storage problem :) Will build some tests in days to come.

**Comment by adrianmay** [comment]
Hi Mati,

Sorry I've been a bit inactive lately. I'm trying to migrate from Taiwan to Britain at very short notice. I'll get back to this within a week or two.

Adrian.

**Comment by adrianmay** [comment]
Silly me. I was checking for undefineds but it was chucking me nulls. Now that's fixed and there's a demo called full.html under demos. I now rethrow as you suggested.
