### ISSUE TITLE
Chrome error, due to Array.prototype.fill

### ISSUE THREAD

**Issue by unikly** [adrianmay/rhaboo#32]
Thanks for the great work, just had some issue with Chrome v44.0.2403.4 dev-m (64-bit).

Due to the addition of Array.prototype.fill(), loop through an array may cause problem, see the following javascript which reproduces error,
```javascript
var a =  ['b', 'c', 'd', 'e'];
for(var i in a){
    alert('Value:'+a[i]);
}
```

**Comment by unematiii** [comment]
Check for `hasOwnProperty` or do not use `for ... in` construct at all.

**Comment by unikly** [comment]
Thanks for the prompt reply, the problem only appears in Chrome for some reason, worked fine in Firefox and IE. We can avoid for ... in loop in our codes, or having type checks in own codes, but it may break 3rd party libs if any of them use the construct to loop array.

**Comment by adrianmay** [comment]
Hi unikly,

Are more standard way to do this is:

  var a =  ['b', 'c', 'd', 'e'];
  for(var i in a){ 
    if (a.hasOwnProperty(i))                                                                                                                                                                      
      console.log('Value:'+a[i]);
  }

Otherwise, for...in lists all the inherited properties as well, except those marked as non-iterable, which I suppose I should do.

Adrian.
