### ISSUE TITLE
Rhaboo adds property `_rhaboo` to JSON

### ISSUE THREAD

**Issue by Download** [adrianmay/rhaboo#33]
Hi thank you for a great library!

I noticed that when calling JSON.stringify on one of the items in my rhaboo store, it included a property _rhaboo with loooooots of data in it... I think it pulls in the whole store.
I read on your site that `hasOwnProperty` was overridden to return `false` for `_rhaboo`... and it does. I checked. Still, the property is included in the JSON. Any idea what I am doing wrong?

**Comment by Download** [comment]
A JS fiddle demonstarting it:  http://jsfiddle.net/he8k7svp/

**Comment by adrianmay** [comment]
Thanks for the tip. The fix is to make _rhaboo non-enumerable instead of hacking hasOwnProperty. I just did that so please try the new version.

**Comment by Download** [comment]
Yes it's fixed, as can be seen from the modified fiddle: http://jsfiddle.net/he8k7svp/7/

Thank you for this! 

It does bring me to another issue though...  
[Rhaboo has no tags/releases](https://github.com/adrianmay/rhaboo/issues/34)
